// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

package com.dropbox.djinni.test;

/**
 * This file tests YAML dumped by Djinni can be parsed back in
 * Record returned by a client
 */
public final class ClientReturnedRecord {


    /*package*/ final long mRecordId;

    /*package*/ final String mContent;

    /*package*/ final String mMisc;

    public ClientReturnedRecord(
            long recordId,
            String content,
            String misc) {
        this.mRecordId = recordId;
        this.mContent = content;
        this.mMisc = misc;
    }

    public long getRecordId() {
        return mRecordId;
    }

    public String getContent() {
        return mContent;
    }

    public String getMisc() {
        return mMisc;
    }

    @Override
    public String toString() {
        return "ClientReturnedRecord{" +
                "mRecordId=" + mRecordId +
                "," + "mContent=" + mContent +
                "," + "mMisc=" + mMisc +
        "}";
    }

}
