// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

package com.dropbox.djinni.test;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class ExternInterface1 {
    public abstract com.dropbox.djinni.test.ClientReturnedRecord foo(com.dropbox.djinni.test.ClientInterface i);

    public abstract com.dropbox.djinni.test.ClientReturnedRecord methTakingRecordList(ArrayList<com.dropbox.djinni.test.ClientReturnedRecord> lr);

    public abstract ArrayList<com.dropbox.djinni.test.ClientReturnedRecord> methReturningRecordList(com.dropbox.djinni.test.ClientReturnedRecord r);

    private static final class CppProxy extends ExternInterface1
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public com.dropbox.djinni.test.ClientReturnedRecord foo(com.dropbox.djinni.test.ClientInterface i)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_foo(this.nativeRef, i);
        }
        private native com.dropbox.djinni.test.ClientReturnedRecord native_foo(long _nativeRef, com.dropbox.djinni.test.ClientInterface i);

        @Override
        public com.dropbox.djinni.test.ClientReturnedRecord methTakingRecordList(ArrayList<com.dropbox.djinni.test.ClientReturnedRecord> lr)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_methTakingRecordList(this.nativeRef, lr);
        }
        private native com.dropbox.djinni.test.ClientReturnedRecord native_methTakingRecordList(long _nativeRef, ArrayList<com.dropbox.djinni.test.ClientReturnedRecord> lr);

        @Override
        public ArrayList<com.dropbox.djinni.test.ClientReturnedRecord> methReturningRecordList(com.dropbox.djinni.test.ClientReturnedRecord r)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_methReturningRecordList(this.nativeRef, r);
        }
        private native ArrayList<com.dropbox.djinni.test.ClientReturnedRecord> native_methReturningRecordList(long _nativeRef, com.dropbox.djinni.test.ClientReturnedRecord r);
    }
}
