// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primtypes.djinni

#pragma once

#include "assorted_primitives.hpp"

namespace testsuite {

public ref class AssortedPrimitives sealed : public Platform::Object {
public:
    property bool B;
    property int8 Eight;
    property int16 Sixteen;
    property int32 Thirtytwo;
    property int64 Sixtyfour;
    property float32 Fthirtytwo;
    property float64 Fsixtyfour;
    property Platform::IBox<bool>^ OB;
    property Platform::IBox<int8>^ OEight;
    property Platform::IBox<int16>^ OSixteen;
    property Platform::IBox<int32>^ OThirtytwo;
    property Platform::IBox<int64>^ OSixtyfour;
    property Platform::IBox<float32>^ OFthirtytwo;
    property Platform::IBox<float64>^ OFsixtyfour;

    AssortedPrimitives(bool B,
                       int8 Eight,
                       int16 Sixteen,
                       int32 Thirtytwo,
                       int64 Sixtyfour,
                       float32 Fthirtytwo,
                       float64 Fsixtyfour,
                       Platform::IBox<bool>^ OB,
                       Platform::IBox<int8>^ OEight,
                       Platform::IBox<int16>^ OSixteen,
                       Platform::IBox<int32>^ OThirtytwo,
                       Platform::IBox<int64>^ OSixtyfour,
                       Platform::IBox<float32>^ OFthirtytwo,
                       Platform::IBox<float64>^ OFsixtyfour) {
        this->B = B;
        this->Eight = Eight;
        this->Sixteen = Sixteen;
        this->Thirtytwo = Thirtytwo;
        this->Sixtyfour = Sixtyfour;
        this->Fthirtytwo = Fthirtytwo;
        this->Fsixtyfour = Fsixtyfour;
        this->OB = OB;
        this->OEight = OEight;
        this->OSixteen = OSixteen;
        this->OThirtytwo = OThirtytwo;
        this->OSixtyfour = OSixtyfour;
        this->OFthirtytwo = OFthirtytwo;
        this->OFsixtyfour = OFsixtyfour;
    }
    AssortedPrimitives() {}
internal:
    ::testsuite::AssortedPrimitives toCpp();
    static AssortedPrimitives^ fromCpp(const ::testsuite::AssortedPrimitives& value);

    bool Equals(AssortedPrimitives^ rhs);
};

}  // namespace testsuite
