// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#pragma once

#include "ClientReturnedRecord.h"
#include <stdint.h>

namespace testsuite {

public interface class IClientInterface
{
public:
    virtual ClientReturnedRecord^ GetRecord (int64 RecordId, Platform::String^ Utf8string, Platform::String^ Misc);
    virtual float64 IdentifierCheck (const Platform::Array<uint8_t>^ Data, int32 R, int64 Jret);
    virtual Platform::String^ ReturnStr ();
    virtual Platform::String^ MethTakingInterface (IClientInterface^ I);
    virtual Platform::String^ MethTakingOptionalInterface (IClientInterface^ I);
};

}  // namespace testsuite
