// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#pragma once

#include "ConstantRecord.h"
#include "constants.hpp"

namespace testsuite {

/** Record containing constants */
public ref class Constants sealed : public Platform::Object {
public:
    property static bool Constants::BoolConstant {bool get() {return true;} } 

    property static uint8_t Constants::I8Constant {uint8_t get() {return 1;} } 

    property static int16_t Constants::I16Constant {int16_t get() {return 2;} } 

    property static int32_t Constants::I32Constant {int32_t get() {return 3;} } 

    property static int64_t Constants::I64Constant {int64_t get() {return 4;} } 

    property static float Constants::F32Constant {float get() {return 5.0f;} } 

    property static double Constants::F64Constant {double get() {return 5.0;} } 

    property static Platform::IBox<bool>^ Constants::OptBoolConstant {Platform::IBox<bool>^ get() {return true;} } 

    property static Platform::IBox<uint8>^ Constants::OptI8Constant {Platform::IBox<uint8>^ get() {return 1;} } 

    property static Platform::IBox<short>^ Constants::OptI16Constant {Platform::IBox<short>^ get() {return 2;} } 

    property static Platform::IBox<int>^ Constants::OptI32Constant {Platform::IBox<int>^ get() {return 3;} } 

    property static Platform::IBox<int64_t>^ Constants::OptI64Constant {Platform::IBox<int64_t>^ get() {return 4;} } 

    property static Platform::IBox<float>^ Constants::OptF32Constant {Platform::IBox<float>^ get() {return 5.0;} } 

    property static Platform::IBox<double>^ Constants::OptF64Constant {Platform::IBox<double>^ get() {return 5.0;} } 

    property static Platform::String^ Constants::StringConstant {Platform::String^ get() {return "string-constant";} } 

    property static Platform::String^ Constants::OptStringConstant {Platform::String^ get() {return "string-constant";} } 

    property static ConstantRecord^ Constants::ObjectConstant {ConstantRecord^ get() {return ref new ConstantRecord(
        Constants::I32Constant /* SomeInteger */ ,
        Constants::StringConstant /* SomeString */ );} } 

    property static bool Constants::Dummy {bool get() {return false;} } 
    Constants() {}
internal:
    ::testsuite::Constants toCpp();
    static Constants^ fromCpp(const ::testsuite::Constants& value);
};

}  // namespace testsuite
