// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#pragma once

#include "ConstantRecord.h"
#include "constants_interface.hpp"
#include <memory>

namespace testsuite {

public ref class ConstantsInterface sealed : public Platform::Object
{
public:
    void Dummy ();
internal:
    ConstantsInterface(std::shared_ptr<::testsuite::ConstantsInterface> cppRef) : _cppRef(cppRef) {}
    std::shared_ptr<::testsuite::ConstantsInterface> cppRef() {return _cppRef;}
private:
    std::shared_ptr<::testsuite::ConstantsInterface> _cppRef;
};

}  // namespace testsuite
