// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#pragma once

#include "Color.h"
#include "enum_usage_record.hpp"

namespace testsuite {

public ref class EnumUsageRecord sealed : public Platform::Object {
public:
    property Color E;
    property Color O;
    property Windows::Foundation::Collections::IVector<Color>^ L;
    property Windows::Foundation::Collections::IIterable<Color>^ S;
    property Windows::Foundation::Collections::IMap<Color, Color>^ M;

    EnumUsageRecord(Color E,
                    Color O,
                    Windows::Foundation::Collections::IVector<Color>^ L,
                    Windows::Foundation::Collections::IIterable<Color>^ S,
                    Windows::Foundation::Collections::IMap<Color, Color>^ M) {
        this->E = E;
        this->O = O;
        this->L = L;
        this->S = S;
        this->M = M;
    }
    EnumUsageRecord() {}
internal:
    ::testsuite::EnumUsageRecord toCpp();
    static EnumUsageRecord^ fromCpp(const ::testsuite::EnumUsageRecord& value);
};

}  // namespace testsuite
