// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#pragma once

#include "ClientInterface.h"
#include "DBClientReturnedRecord.h"
#include "extern_interface_1.hpp"
#include <memory>

namespace testsuite {

public ref class ExternInterface1 sealed : public Platform::Object
{
public:
    ClientReturnedRecord^ Foo (ClientInterface^ I);
    ClientReturnedRecord^ MethTakingRecordList (Windows::Foundation::Collections::IVector<ClientReturnedRecord^>^ Lr);
    Windows::Foundation::Collections::IVector<ClientReturnedRecord^>^ MethReturningRecordList (ClientReturnedRecord^ R);
internal:
    ExternInterface1(std::shared_ptr<::ExternInterface1> cppRef) : _cppRef(cppRef) {}
    std::shared_ptr<::ExternInterface1> cppRef() {return _cppRef;}
private:
    std::shared_ptr<::ExternInterface1> _cppRef;
};

}  // namespace testsuite
