// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#pragma once

#include "ExternRecordWithDerivings.h"
#include "TestHelpers.h"

namespace testsuite {

public interface class ExternInterface2
{
public:
    virtual ExternRecordWithDerivings^ Foo (::testsuite::TestHelpers^ I);
};

}  // namespace testsuite
