// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#include "InterfaceUsingExtendedRecord.h"  // my header
#include "ExtendedRecord.h"
#include "RecordUsingExtendedRecord.h"
#include "translation.h"

namespace testsuite {

RecordUsingExtendedRecord^ const InterfaceUsingExtendedRecord::Cr = ref new (RecordUsingExtendedRecord,true)(
    ref new (ExtendedRecord,true)(
        false /* Foo */ ) /* Er */ );
ExtendedRecord^ InterfaceUsingExtendedRecord::Meth (ExtendedRecord^ Er)
{
    try {
        auto cppRet = _cppRef->meth(transform<::testsuite::ExtendedRecord, ::testsuite::ExtendedRecord^>()(Er));
        return transform<::testsuite::ExtendedRecord, ::testsuite::ExtendedRecord^>()(cppRet);
    }
    catch(const std::exception& e) {
        throw ref new Platform::Exception(-1, transform<std::string, Platform::String^>()((std::string)e.what()));
    }
}

}  // namespace testsuite
