// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#pragma once

#include "ExtendedRecord.h"
#include "RecordUsingExtendedRecord.h"
#include "interface_using_extended_record.hpp"
#include <memory>

namespace testsuite {

public ref class InterfaceUsingExtendedRecord sealed : public Platform::Object
{
public:
    ExtendedRecord^ Meth (ExtendedRecord^ Er);
internal:
    InterfaceUsingExtendedRecord(std::shared_ptr<::testsuite::InterfaceUsingExtendedRecord> cppRef) : _cppRef(cppRef) {}
    std::shared_ptr<::testsuite::InterfaceUsingExtendedRecord> cppRef() {return _cppRef;}
private:
    std::shared_ptr<::testsuite::InterfaceUsingExtendedRecord> _cppRef;
};

}  // namespace testsuite
