// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

#pragma once

#include "map_record.hpp"

namespace testsuite {

public ref class MapRecord sealed : public Platform::Object {
public:
    property Windows::Foundation::Collections::IMap<Platform::String^, int64>^ Map;
    property Windows::Foundation::Collections::IMap<int32, int32>^ Imap;

    MapRecord(Windows::Foundation::Collections::IMap<Platform::String^, int64>^ Map,
              Windows::Foundation::Collections::IMap<int32, int32>^ Imap) {
        this->Map = Map;
        this->Imap = Imap;
    }
    MapRecord() {}
internal:
    ::testsuite::MapRecord toCpp();
    static MapRecord^ fromCpp(const ::testsuite::MapRecord& value);
};

}  // namespace testsuite
