// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from derivings.djinni

#pragma once

#include "record_with_derivings.hpp"

namespace testsuite {

public ref class RecordWithDerivings sealed : public Platform::Object {
public:
    property int8 Eight;
    property int16 Sixteen;
    property int32 Thirtytwo;
    property int64 Sixtyfour;
    property float Fthirtytwo;
    property double Fsixtyfour;
    property Windows::Foundation::DateTime^ D;
    property Platform::String^ S;

    RecordWithDerivings(int8 Eight,
                        int16 Sixteen,
                        int32 Thirtytwo,
                        int64 Sixtyfour,
                        float Fthirtytwo,
                        double Fsixtyfour,
                        Windows::Foundation::DateTime^ D,
                        Platform::String^ S) {
        this->Eight = Eight;
        this->Sixteen = Sixteen;
        this->Thirtytwo = Thirtytwo;
        this->Sixtyfour = Sixtyfour;
        this->Fthirtytwo = Fthirtytwo;
        this->Fsixtyfour = Fsixtyfour;
        this->D = D;
        this->S = S;
    }
    RecordWithDerivings() {}
internal:
    ::testsuite::RecordWithDerivings toCpp();
    static RecordWithDerivings^ fromCpp(const ::testsuite::RecordWithDerivings& value);

    bool Equals(RecordWithDerivings^ rhs);

    int32 CompareTo(RecordWithDerivings^ rhs);
};

}  // namespace testsuite
