// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#pragma once

#include "reverse_client_interface.hpp"
#include <memory>

namespace testsuite {

public ref class ReverseClientInterface sealed : public Platform::Object
{
public:
    Platform::String^ ReturnStr ();
    Platform::String^ MethTakingInterface (IReverseClientInterface^ I);
    Platform::String^ MethTakingOptionalInterface (Platform::IBox<IReverseClientInterface>^ I);
    static IReverseClientInterface^ Create ();
internal:
    ReverseClientInterface(std::shared_ptr<::testsuite::ReverseClientInterface> cppRef) : _cppRef(cppRef) {}
    std::shared_ptr<::testsuite::ReverseClientInterface> cppRef() {return _cppRef;}
private:
    std::shared_ptr<::testsuite::ReverseClientInterface> _cppRef;
};

}  // namespace testsuite
