// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from set.djinni

#pragma once

#include "set_record.hpp"

namespace testsuite {

public ref class SetRecord sealed : public Platform::Object {
public:
    property Windows::Foundation::Collections::IIterable<Platform::String^>^ Set;
    property Windows::Foundation::Collections::IIterable<int32>^ Iset;

    SetRecord(Windows::Foundation::Collections::IIterable<Platform::String^>^ Set,
              Windows::Foundation::Collections::IIterable<int32>^ Iset) {
        this->Set = Set;
        this->Iset = Iset;
    }
    SetRecord() {}
internal:
    ::testsuite::SetRecord toCpp();
    static SetRecord^ fromCpp(const ::testsuite::SetRecord& value);
};

}  // namespace testsuite
