// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wchar_test.djinni

#include "WcharTestHelpers.h"  // my header
#include "WcharTestRec.h"
#include "translation.h"

namespace testsuite {

WcharTestRec^ WcharTestHelpers::GetRecord ()
{
    try {
        auto cppRet = ::testsuite::WcharTestHelpers::get_record();
        return transform<::testsuite::WcharTestRec, ::testsuite::WcharTestRec^>()(cppRet);
    }
    catch(const std::exception& e) {
        throw ref new Platform::Exception(-1, transform<std::string, Platform::String^>()((std::string)e.what()));
    }
}
Platform::String^ WcharTestHelpers::GetString ()
{
    try {
        auto cppRet = ::testsuite::WcharTestHelpers::get_string();
        return transform<std::wstring, Platform::String^>()(cppRet);
    }
    catch(const std::exception& e) {
        throw ref new Platform::Exception(-1, transform<std::string, Platform::String^>()((std::string)e.what()));
    }
}
bool WcharTestHelpers::CheckString (Platform::String^ Str)
{
    try {
        auto cppRet = ::testsuite::WcharTestHelpers::check_string(transform<std::wstring, Platform::String^>()(Str));
        return transform<bool, bool>()(cppRet);
    }
    catch(const std::exception& e) {
        throw ref new Platform::Exception(-1, transform<std::string, Platform::String^>()((std::string)e.what()));
    }
}
bool WcharTestHelpers::CheckRecord (WcharTestRec^ Rec)
{
    try {
        auto cppRet = ::testsuite::WcharTestHelpers::check_record(transform<::testsuite::WcharTestRec, ::testsuite::WcharTestRec^>()(Rec));
        return transform<bool, bool>()(cppRet);
    }
    catch(const std::exception& e) {
        throw ref new Platform::Exception(-1, transform<std::string, Platform::String^>()((std::string)e.what()));
    }
}

}  // namespace testsuite
