// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#import "DBClientInterface.h"
#import "DBClientReturnedRecord.h"
#import <Foundation/Foundation.h>


@interface DBExternInterface1 : NSObject

- (nonnull DBClientReturnedRecord *)foo:(nullable id<DBClientInterface>)i;

- (nonnull DBClientReturnedRecord *)methTakingRecordList:(nonnull NSArray<DBClientReturnedRecord *> *)lr;

- (nonnull NSArray<DBClientReturnedRecord *> *)methReturningRecordList:(nonnull DBClientReturnedRecord *)r;

@end
